/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ChessGameStandaloneSetup extends ChessGameStandaloneSetupGenerated {

	public static void doSetup() {
		new ChessGameStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
