/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.chessgame.ui.internal.ChessgameActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ChessGameExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(ChessgameActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		ChessgameActivator activator = ChessgameActivator.getInstance();
		return activator != null ? activator.getInjector(ChessgameActivator.UK_AC_KCL_INF_CHESSGAME_CHESSGAME) : null;
	}

}
