/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.chessgame.parser.antlr.internal.InternalChessGameParser;
import uk.ac.kcl.inf.chessgame.services.ChessGameGrammarAccess;

public class ChessGameParser extends AbstractAntlrParser {

	@Inject
	private ChessGameGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalChessGameParser createParser(XtextTokenStream stream) {
		return new InternalChessGameParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ChessProgram";
	}

	public ChessGameGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ChessGameGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
