/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell Display</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.CellDisplay#getText <em>Text</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.CellDisplay#getColor <em>Color</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellDisplay()
 * @model
 * @generated
 */
public interface CellDisplay extends EObject
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellDisplay_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.CellDisplay#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

  /**
   * Returns the value of the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Color</em>' attribute.
   * @see #setColor(String)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellDisplay_Color()
   * @model
   * @generated
   */
  String getColor();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.CellDisplay#getColor <em>Color</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Color</em>' attribute.
   * @see #getColor()
   * @generated
   */
  void setColor(String value);

} // CellDisplay
