/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Cell State</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.CellState#getName <em>Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.CellState#getDisplay <em>Display</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.CellState#getTransitions <em>Transitions</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellState()
 * @model
 * @generated
 */
public interface CellState extends Statements
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellState_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.CellState#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Display</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Display</em>' containment reference.
   * @see #setDisplay(CellDisplay)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellState_Display()
   * @model containment="true"
   * @generated
   */
  CellDisplay getDisplay();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.CellState#getDisplay <em>Display</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Display</em>' containment reference.
   * @see #getDisplay()
   * @generated
   */
  void setDisplay(CellDisplay value);

  /**
   * Returns the value of the '<em><b>Transitions</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.chessgame.chessGame.Transition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transitions</em>' containment reference list.
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getCellState_Transitions()
   * @model containment="true"
   * @generated
   */
  EList<Transition> getTransitions();

} // CellState
