/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chess Program</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.ChessProgram#getStatements <em>Statements</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getChessProgram()
 * @model
 * @generated
 */
public interface ChessProgram extends EObject
{
  /**
   * Returns the value of the '<em><b>Statements</b></em>' containment reference list.
   * The list contents are of type {@link uk.ac.kcl.inf.chessgame.chessGame.Statements}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statements</em>' containment reference list.
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getChessProgram_Statements()
   * @model containment="true"
   * @generated
   */
  EList<Statements> getStatements();

} // ChessProgram
