/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.ContextExpression#getSub_exp <em>Sub exp</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.ContextExpression#getCellState <em>Cell State</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getContextExpression()
 * @model
 * @generated
 */
public interface ContextExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Sub exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sub exp</em>' containment reference.
   * @see #setSub_exp(StateFilterExpression)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getContextExpression_Sub_exp()
   * @model containment="true"
   * @generated
   */
  StateFilterExpression getSub_exp();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.ContextExpression#getSub_exp <em>Sub exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sub exp</em>' containment reference.
   * @see #getSub_exp()
   * @generated
   */
  void setSub_exp(StateFilterExpression value);

  /**
   * Returns the value of the '<em><b>Cell State</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cell State</em>' containment reference.
   * @see #setCellState(EmptyExpression)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getContextExpression_CellState()
   * @model containment="true"
   * @generated
   */
  EmptyExpression getCellState();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.ContextExpression#getCellState <em>Cell State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cell State</em>' containment reference.
   * @see #getCellState()
   * @generated
   */
  void setCellState(EmptyExpression value);

} // ContextExpression
