/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>height</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.height#getHEIGHT <em>HEIGHT</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getheight()
 * @model
 * @generated
 */
public interface height extends Statements
{
  /**
   * Returns the value of the '<em><b>HEIGHT</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>HEIGHT</em>' attribute.
   * @see #setHEIGHT(int)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getheight_HEIGHT()
   * @model
   * @generated
   */
  int getHEIGHT();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.height#getHEIGHT <em>HEIGHT</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>HEIGHT</em>' attribute.
   * @see #getHEIGHT()
   * @generated
   */
  void setHEIGHT(int value);

} // height
