/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Transition Spec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.TransitionSpec#getTrigger <em>Trigger</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.TransitionSpec#getTarget <em>Target</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getTransitionSpec()
 * @model
 * @generated
 */
public interface TransitionSpec extends EObject
{
  /**
   * Returns the value of the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trigger</em>' containment reference.
   * @see #setTrigger(MouseTrigger)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getTransitionSpec_Trigger()
   * @model containment="true"
   * @generated
   */
  MouseTrigger getTrigger();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.TransitionSpec#getTrigger <em>Trigger</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trigger</em>' containment reference.
   * @see #getTrigger()
   * @generated
   */
  void setTrigger(MouseTrigger value);

  /**
   * Returns the value of the '<em><b>Target</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target</em>' reference.
   * @see #setTarget(CellState)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getTransitionSpec_Target()
   * @model
   * @generated
   */
  CellState getTarget();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.TransitionSpec#getTarget <em>Target</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target</em>' reference.
   * @see #getTarget()
   * @generated
   */
  void setTarget(CellState value);

} // TransitionSpec
