/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>width</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.width#getWIDTH <em>WIDTH</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getwidth()
 * @model
 * @generated
 */
public interface width extends Statements
{
  /**
   * Returns the value of the '<em><b>WIDTH</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>WIDTH</em>' attribute.
   * @see #setWIDTH(int)
   * @see uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage#getwidth_WIDTH()
   * @model
   * @generated
   */
  int getWIDTH();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.chessgame.chessGame.width#getWIDTH <em>WIDTH</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>WIDTH</em>' attribute.
   * @see #getWIDTH()
   * @generated
   */
  void setWIDTH(int value);

} // width
