/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import uk.ac.kcl.inf.chessgame.chessGame.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class ChessGameFactoryImpl extends EFactoryImpl implements ChessGameFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static ChessGameFactory init()
  {
    try
    {
      ChessGameFactory theChessGameFactory = (ChessGameFactory)EPackage.Registry.INSTANCE.getEFactory(ChessGamePackage.eNS_URI);
      if (theChessGameFactory != null)
      {
        return theChessGameFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new ChessGameFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChessGameFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case ChessGamePackage.CHESS_PROGRAM: return createChessProgram();
      case ChessGamePackage.FIELD_SPECIFICATION: return createFieldSpecification();
      case ChessGamePackage.OPTION_SPECIFICATION: return createOptionSpecification();
      case ChessGamePackage.CELL_STATE: return createCellState();
      case ChessGamePackage.CELL_DISPLAY_SPEC: return createCellDisplaySpec();
      case ChessGamePackage.TRANSITION_SPEC: return createTransitionSpec();
      case ChessGamePackage.MOUSE_TRIGGER: return createMouseTrigger();
      case ChessGamePackage.GAME_END: return createGameEnd();
      case ChessGamePackage.CONTEXT_EXPRESSION: return createContextExpression();
      case ChessGamePackage.STATE_FILTER_EXPRESSION: return createStateFilterExpression();
      case ChessGamePackage.EMPTY_EXPRESSION: return createEmptyExpression();
      case ChessGamePackage.END_BEHAVIOUR: return createEndBehaviour();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ChessProgram createChessProgram()
  {
    ChessProgramImpl chessProgram = new ChessProgramImpl();
    return chessProgram;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FieldSpecification createFieldSpecification()
  {
    FieldSpecificationImpl fieldSpecification = new FieldSpecificationImpl();
    return fieldSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public OptionSpecification createOptionSpecification()
  {
    OptionSpecificationImpl optionSpecification = new OptionSpecificationImpl();
    return optionSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CellState createCellState()
  {
    CellStateImpl cellState = new CellStateImpl();
    return cellState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CellDisplaySpec createCellDisplaySpec()
  {
    CellDisplaySpecImpl cellDisplaySpec = new CellDisplaySpecImpl();
    return cellDisplaySpec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TransitionSpec createTransitionSpec()
  {
    TransitionSpecImpl transitionSpec = new TransitionSpecImpl();
    return transitionSpec;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MouseTrigger createMouseTrigger()
  {
    MouseTriggerImpl mouseTrigger = new MouseTriggerImpl();
    return mouseTrigger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public GameEnd createGameEnd()
  {
    GameEndImpl gameEnd = new GameEndImpl();
    return gameEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ContextExpression createContextExpression()
  {
    ContextExpressionImpl contextExpression = new ContextExpressionImpl();
    return contextExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StateFilterExpression createStateFilterExpression()
  {
    StateFilterExpressionImpl stateFilterExpression = new StateFilterExpressionImpl();
    return stateFilterExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EmptyExpression createEmptyExpression()
  {
    EmptyExpressionImpl emptyExpression = new EmptyExpressionImpl();
    return emptyExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EndBehaviour createEndBehaviour()
  {
    EndBehaviourImpl endBehaviour = new EndBehaviourImpl();
    return endBehaviour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ChessGamePackage getChessGamePackage()
  {
    return (ChessGamePackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static ChessGamePackage getPackage()
  {
    return ChessGamePackage.eINSTANCE;
  }

} //ChessGameFactoryImpl
