/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage;
import uk.ac.kcl.inf.chessgame.chessGame.ContextExpression;
import uk.ac.kcl.inf.chessgame.chessGame.EmptyExpression;
import uk.ac.kcl.inf.chessgame.chessGame.StateFilterExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Context Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.impl.ContextExpressionImpl#getSub_exp <em>Sub exp</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.impl.ContextExpressionImpl#getCellState <em>Cell State</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContextExpressionImpl extends MinimalEObjectImpl.Container implements ContextExpression
{
  /**
   * The cached value of the '{@link #getSub_exp() <em>Sub exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSub_exp()
   * @generated
   * @ordered
   */
  protected StateFilterExpression sub_exp;

  /**
   * The cached value of the '{@link #getCellState() <em>Cell State</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCellState()
   * @generated
   * @ordered
   */
  protected EmptyExpression cellState;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContextExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ChessGamePackage.Literals.CONTEXT_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StateFilterExpression getSub_exp()
  {
    return sub_exp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSub_exp(StateFilterExpression newSub_exp, NotificationChain msgs)
  {
    StateFilterExpression oldSub_exp = sub_exp;
    sub_exp = newSub_exp;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP, oldSub_exp, newSub_exp);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSub_exp(StateFilterExpression newSub_exp)
  {
    if (newSub_exp != sub_exp)
    {
      NotificationChain msgs = null;
      if (sub_exp != null)
        msgs = ((InternalEObject)sub_exp).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP, null, msgs);
      if (newSub_exp != null)
        msgs = ((InternalEObject)newSub_exp).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP, null, msgs);
      msgs = basicSetSub_exp(newSub_exp, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP, newSub_exp, newSub_exp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EmptyExpression getCellState()
  {
    return cellState;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCellState(EmptyExpression newCellState, NotificationChain msgs)
  {
    EmptyExpression oldCellState = cellState;
    cellState = newCellState;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE, oldCellState, newCellState);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCellState(EmptyExpression newCellState)
  {
    if (newCellState != cellState)
    {
      NotificationChain msgs = null;
      if (cellState != null)
        msgs = ((InternalEObject)cellState).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE, null, msgs);
      if (newCellState != null)
        msgs = ((InternalEObject)newCellState).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE, null, msgs);
      msgs = basicSetCellState(newCellState, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE, newCellState, newCellState));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP:
        return basicSetSub_exp(null, msgs);
      case ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE:
        return basicSetCellState(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP:
        return getSub_exp();
      case ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE:
        return getCellState();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP:
        setSub_exp((StateFilterExpression)newValue);
        return;
      case ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE:
        setCellState((EmptyExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP:
        setSub_exp((StateFilterExpression)null);
        return;
      case ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE:
        setCellState((EmptyExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ChessGamePackage.CONTEXT_EXPRESSION__SUB_EXP:
        return sub_exp != null;
      case ChessGamePackage.CONTEXT_EXPRESSION__CELL_STATE:
        return cellState != null;
    }
    return super.eIsSet(featureID);
  }

} //ContextExpressionImpl
