/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.chessGame.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import uk.ac.kcl.inf.chessgame.chessGame.CellState;
import uk.ac.kcl.inf.chessgame.chessGame.ChessGamePackage;
import uk.ac.kcl.inf.chessgame.chessGame.StateFilterExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>State Filter Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.chessgame.chessGame.impl.StateFilterExpressionImpl#getCell_state <em>Cell state</em>}</li>
 * </ul>
 *
 * @generated
 */
public class StateFilterExpressionImpl extends MinimalEObjectImpl.Container implements StateFilterExpression
{
  /**
   * The cached value of the '{@link #getCell_state() <em>Cell state</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCell_state()
   * @generated
   * @ordered
   */
  protected CellState cell_state;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected StateFilterExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ChessGamePackage.Literals.STATE_FILTER_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CellState getCell_state()
  {
    if (cell_state != null && cell_state.eIsProxy())
    {
      InternalEObject oldCell_state = (InternalEObject)cell_state;
      cell_state = (CellState)eResolveProxy(oldCell_state);
      if (cell_state != oldCell_state)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, ChessGamePackage.STATE_FILTER_EXPRESSION__CELL_STATE, oldCell_state, cell_state));
      }
    }
    return cell_state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CellState basicGetCell_state()
  {
    return cell_state;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCell_state(CellState newCell_state)
  {
    CellState oldCell_state = cell_state;
    cell_state = newCell_state;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, ChessGamePackage.STATE_FILTER_EXPRESSION__CELL_STATE, oldCell_state, cell_state));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case ChessGamePackage.STATE_FILTER_EXPRESSION__CELL_STATE:
        if (resolve) return getCell_state();
        return basicGetCell_state();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case ChessGamePackage.STATE_FILTER_EXPRESSION__CELL_STATE:
        setCell_state((CellState)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case ChessGamePackage.STATE_FILTER_EXPRESSION__CELL_STATE:
        setCell_state((CellState)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case ChessGamePackage.STATE_FILTER_EXPRESSION__CELL_STATE:
        return cell_state != null;
    }
    return super.eIsSet(featureID);
  }

} //StateFilterExpressionImpl
