/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.ide;


/**
 * Use this class to register ide components.
 */
public class ChessGameIdeModule extends AbstractChessGameIdeModule {
}
