/*
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractChessGameScopeProvider extends DelegatingScopeProvider {
}
