/**
 * generated by Xtext 2.24.0
 */
package uk.ac.kcl.inf.chessgame;

import uk.ac.kcl.inf.chessgame.AbstractChessGameRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class ChessGameRuntimeModule extends AbstractChessGameRuntimeModule {
}
